AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with spring boot.

Resources:
  PsipherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.psipher.application.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/psipher-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: [AWSLambdaBasicExecutionRole, AWSLambdaDynamoDBExecutionRole, AmazonDynamoDBFullAccess, AWSKeyManagementServicePowerUser]
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

  PsipherDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "UserDetails"

Outputs:
  SpringBootPsipherApi:
    Description: URL for application /ping can be replaced by the url mapped
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/ping'
    Export:
      Name: SpringBootPsipherApi
